import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/commons/navbar";
import Footer from "@/components/commons/footer";
import { Toaster } from "sonner";
import AuthProvider from "@/provider/auth-provider";
import CartContextProvider from "@/provider/cart-provider";
import WishlistContextProvider from "@/provider/wishlist-provider";

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
  <body className={`${exo.variable} antialiased`}>
    <AuthProvider>
      <CartContextProvider>
        <WishlistContextProvider>
          <Navbar />
          {children}
          <Toaster position="top-center" richColors expand={false} toastOptions={{ duration: 2000 }} />
          <Footer />
        </WishlistContextProvider>
      </CartContextProvider>
    </AuthProvider>
  </body>
</html>
  );
}
